name: moltis
version: '0.2.0'
summary: Personal AI gateway inspired by OpenClaw
description: |
  Moltis is a personal AI gateway inspired by OpenClaw. One binary, multiple LLM providers.

base: core24
grade: stable
confinement: strict

platforms:
  amd64:
  arm64:

apps:
  moltis:
    command: bin/moltis
    plugs:
      - network
      - network-bind

parts:
  moltis:
    plugin: rust
    source: .
    rust-path: ["crates/cli"]
    build-packages:
      - pkg-config
      - libssl-dev
      - cmake
      - build-essential
      - libclang-dev
      - git
